"""allow multiple emergency contacts per patient

Revision ID: multi_contact_v1
Revises: visit_summary_v1
Create Date: 2026-08-09

Drops the unique constraint on emergency_contact.patient_id so a patient
can have more than one emergency contact. The constraint name is
discovered dynamically at migration time rather than hardcoded, since it
was auto-generated by Postgres when the table was first created (before
Alembic was adopted) and the exact generated name isn't something we can
be fully certain of in advance.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect

revision = 'multi_contact_v1'
down_revision = 'visit_summary_v1'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa_inspect(conn)
    unique_constraints = inspector.get_unique_constraints('emergency_contact')
    for uc in unique_constraints:
        if uc['column_names'] == ['patient_id'] and uc['name']:
            op.drop_constraint(uc['name'], 'emergency_contact', type_='unique')


def downgrade():
    op.create_unique_constraint('uq_emergency_contact_patient_id', 'emergency_contact', ['patient_id'])
